# Generated by Django 3.2 on 2021-05-06 14:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('levelupapi', '0003_event_time'),
    ]

    operations = [
        migrations.AddField(
            model_name='game',
            name='maker',
            field=models.CharField(default='John', max_length=50),
            preserve_default=False,
        ),
    ]
